server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/poa?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

#  servlet:
#    context-path: /
#    encoding:
#      charset: utf-8
#  compression:
#    enabled: true
#    mime-types: application/json
#    min-response-size: 500
#  shutdown: graceful
#
#mybatis:
#  mapper-locations: classpath:sql/*.xml
#
#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#
#feign:
#  client:
#    config:
#      default:
#        decode404: false
#        loggerLevel: full
#        connect-timeout: 5000
#        readTimeout: 10000
#  compression:
#    request:
#      enabled: true
#      mime-types: application/json
#      min-request-size: 2048
#    response.enabled: true

---

#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    hikari:
#      jdbc-url: ENC(LRGay7jUqVCCsWHUSkUHrlZh4nvlWP1O0FWION3MIl0V15muHrnySR0KrGGu3WK5vvXLxpCrIPXaeKTkT4J1ci0oY/UsTR/H0l9JsMimU/I=)
#      username: ENC(Qx5FmpXykhQsw5iB2vrY8A==)
#      password: ENC(KJB9k9KsL8aJA+xIigxwmcnUOIr+kYBX)
#      connectionTimeout: 10000
#      maximumPoolSize: 1
#      max-lifetime: 600000
#      poolName: openapi-pool
#      connection-test-query: select 1
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDataSource
#
#springdoc:
#  swagger-ui:
#    enabled: true
#    operations-sorter: alpha
#    tags-sorter: alpha
#    defaultModelsExpandDepth: -1
#    server-url: http://localhost:8080
#    description: description.txt
