server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://[AWS RDS 주소]:3306/poa?characterEncoding=UTF-8&serverTimezone=UTC
    username: [ID]
    password: [PW]

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      location: C:\\img

cloud:
  aws:
    credentials:
      accessKey: [AWS S3 액세스키]
      secretKey: [AWS S3 시크릿키]
    s3:
      bucket: poa-s3-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false